// models/conversation.model.js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const conversationSchema = new Schema({
    // _id will be automatically generated by MongoDB
    user_id: { type: String, required: true },
    title: { type: String, default: 'New Chat' }
}, {
    // This option automatically adds `createdAt` and `updatedAt` fields
    timestamps: true 
});

const Conversation = mongoose.model('Conversation', conversationSchema);
module.exports = Conversation;